export const GET_RECIPIES = '[GET_RECIPIES]';

export const CREATE_RECIPE = '[CREATE_RECIPE]';
export const MODIFY_RECIPE = '[MODIFY_RECIPE]';
export const REMOVE_RECIPE = '[REMOVE_RECIPE]';
export const ACTIVE_RECIPE = '[ACTIVE_RECIPE]';
export const REMOVE_ACTIVE_RECIPE = '[REMOVE_ACTIVE_RECIPE]';
